server:
  max-http-request-header-size: 64KB
hapi:
  fhir:
    # server_address: http://localhost:8080/fhir
    # server_address: https://hapi-fhir.au.localhost/fhir
    server_address: http://hapi-fhir.au.localhost/fhir
    default_encoding: json
    # dao_config.server_id_mode: UUID