services:

  apisix:
    container_name: apisix
    build:
      context: ./services/apisix
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - '${PWD}/services/apisix/conf/config.yml:/usr/local/apisix/conf/config.yaml:ro'
      - '${PWD}/services/apisix/conf/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro'
    ports:
      - 80:80
      - 443:443-
      # - 9080:9080
    depends_on:
      keycloak.au.localhost:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - hapi_fhir_network
    env_file:
      - ./.env

  postgres:
    container_name: postgres
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 10s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - hapi_fhir_network
    env_file:
      - ./.env

  # keycloak
  #   container_name: keycloak
  keycloak.au.localhost:
    container_name: keycloak.au.localhost
    build:
      context: ./services/keycloak
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/keycloak/health-check.sh"]
      start_period: 10s
      interval: 30s
      retries: 5
      timeout: 5s

    # 'start-dev',
    # 'start',
    # '-Dauto-build',
    # '--log-level=INFO,io.vertx.ext.web.impl.RouterImpl:TRACE',

    # '-Dkeycloak.migration.action=import',
    # '-Dkeycloak.migration.provider=singleFile',
    # '-Dkeycloak.migration.realmName=hapi-fhir-dev',
    # '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
    # '-Dkeycloak.migration.file=/import/development-realm.json',

    command:
      [
        'start',
        '--log-level=INFO,io.vertx.ext.web.impl.RouterImpl:TRACE',
      ]

    environment:

      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}

      KC_HTTPS_CERTIFICATE_FILE: /etc/keycloak/certs/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/keycloak/certs/key.pem

      KC_PROXY_HEADERS: forwarded

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-secret}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HEALTH_ENABLED: true

    # Make sure the certificate and the key (the *.pem files) have the correct permissions -> e.g., sudo chmod 655 *.pem
    volumes:
      - '${PWD}/services/keycloak/scripts/health-check.sh:/opt/keycloak/health-check.sh'
      - '${PWD}/certs/keycloak-cert.pem:/etc/keycloak/certs/cert.pem'
      - '${PWD}/certs/keycloak-key.pem:/etc/keycloak/certs/key.pem'
      - '${PWD}/certs:/opt/keycloak/conf/truststores'
      - '${PWD}:/import'
    ports:
      - 8443:8443
      - 9000:9000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hapi_fhir_network
    env_file:
      - ./.env

  hapi-fhir:
    container_name: hapi-fhir
    build:
      context: ./services/hapi-fhir
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-hapi-fhir}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-admin}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      SPRING_DATASOURCE_DRIVERCLASSNAME: 'org.postgresql.Driver'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect'
    expose:
      - 80:80
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      postgres:
        condition: service_healthy
      keycloak.au.localhost:
        condition: service_healthy
    networks:
      - hapi_fhir_network
    env_file:
      - ./.env

networks:
  hapi_fhir_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

configs:
  hapi:
    file: ./hapi.application.yaml
    # file: ./hapi.application-fhir-au-core-1.0.0-preview.yaml
